# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-22.04-desktop"
  config.vm.box_url = "file://#{Dir.home()}/1git/virtual-machines/boxes/ubuntu-22.04-desktop.json"

  config.vm.provider "virtualbox" do |v|
    v.name = "ubuntu-22.04-desktop"
    v.gui = true
    v.memory = 4096
    v.customize ["setextradata", :id, "CustomVideoMode1", "1920x1080x32"]
    v.customize ["setextradata", :id, "GUI/Fullscreen", "on"]
    v.customize ["setextradata", :id, "GUI/MiniToolBarAlignment", "top"]
  end
end
